### ISSUE TITLE
Tulip.xml not found

### ISSUE THREAD

**Issue by LarsNorgaard** [atiprusma/CAIO#1]
The installer says it can't find the tulip.xml file.

- Copying zip to temp directory
- Installing [UnF]_Camera_All-in-One-XV_(2019-04-18).zip
- Mounting /system, /vendor
Archive:  /data/user/0/com.s.iCFbpta.dS7.bD/cache/install.zip
  inflating: system.prop
  inflating: unity_install.sh
  inflating: unity_uninstall.sh
  inflating: unity_upgrade.sh
  inflating: busybox
  inflating: busybox
  inflating: util_functions.sh
  inflating: install.sh
  inflating: module.prop
  inflating: uninstall.sh
 
Unzipping files...
    *******************************************
    *         [UnF] Camera All-in-One         *
    *******************************************
    *             XV (2019-04-18)             *
    *by atiprusma @ TG, Hadinata @ Ancient Family*
    *******************************************
 
    *******************************************
    *       Shoutout to TadiT7 @ github       *
    *       for NUMEROUS Stock ROM dumps      *
    *******************************************
 
- MagiskSU detected
 
- Debug mode
  Debug log will be written to: /sdcard/CAIO-debug.log
 
- Your Redmi Note 6 Pro (tulip) is supported
 
- Installing
 
- Running Preinstall Addons -
  Running Volume-Key-Selector...
- Vol Key Test -
  Press a Vol Key
 
- Preinstalling (cont) -
 
- Detecting ROM -
 
- xiaomi.eu is MIUI based -
- AOSP/LOS patches will be skipped -
 
  Extracting CAIO base files...
 
- Disable EIS? -
  Vol+ (Yes)  /  Vol- (No)
 
  > EIS Enabled
 
- Disable Gimmick AI (selfie, square and portrait)? -
  Vol+ (Yes)  /  Vol- (No)
 
  > Gimmick AI enabled
  ! tulip.xml not found !
! Installation failed

**Comment by atiprusma** [comment]
i fixed miui xml copying on yesterday's update
